###########
# site.title, site.url, site.author.name

title:   'nightcrawler.me'
author:  
  name:  'nightcrawler'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: 'http://nightcrawler086.github.io'
url:  'http://blog.nightcrawler.me'


########
# more settings

markdown: kramdown

# highlighter
highlighter: pygments

sass:
  sass_dir: css
  style:    expanded

permalink: date

exclude:
- README.md


safe: true
lsi: false

