###########
# site.title, site.url, site.author.name

title:   'nightcrawler.me'
author:  
  name:  'nightcrawler'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: 'http://nightcrawler086.github.io'
url:  'http://blog.nightcrawler.me'

# About
author:
	name:  Brian Hall
	url: https://twitter.com/nightcrawler086
	email: brian.hall4@gmail.com
	github: nightcrawler086
	twitter: nightcrawler086

# Gems
gems:
	- jekyll-paginate

# pagination
#paginate: 5
#paginate_path: "/blog/page:num/"


########
# more settings

markdown: kramdown

# highlighter
highlighter: pygments

sass:
  sass_dir: css
  style:    expanded

# permalink
permalink: /:year/:month/:day/:title
relative_permalinks: true

exclude:
- README.md


safe: true
lsi: false

