# Site Info
name: nightcrawler.me
descrtiption: a blog about anything from enterprise storage, virtulaization, linux, OSX, and anything in-between

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            nightcrawler.me
tagline:          'a technology blog'
description:      'a blog about anything from enterprise storage, virtulaization, linux, OSX, and anything in-between'
url:              http://blog.nightcrawler.me
baseurl:          /

author:
  name:           'Brian Hall'
  url:            https://twitter.com/nightcrawler086
  twitter:        nightcrawler086
  linkedin:       bhall4
  github:		  nightcrawler086

paginate:         5

# Custom vars
version:          2.1.0

